- name: Gather Linux System Information
  hosts: linux  # or your specific group of Linux hosts
  gather_facts: false

  tasks:
    - name: Get kernel version
      ansible.builtin.command: uname -a
      register: kernel_info

    - name: Display kernel version
      ansible.builtin.debug:
        msg: "{{ kernel_info.stdout }}"

    - name: Get OS details
      ansible.builtin.slurp:
        src: /etc/os-release
      register: os_release

    - name: Display OS details
      ansible.builtin.debug:
        msg: "{{ (os_release.content | b64decode).split('\n') }}"

- name: Gather Windows OS info
  hosts: windows 
  gather_facts: false
  
  tasks: 
    - name: Get OS info 
      ansible.windows.win_command: systeminfo
      register: windows_os_info

    - name: Show OS info
      ansible.builtin.debug: 
        msg: "{{ windows_os_info }}"